site_name: CS255 Computer Security Lab 4

markdown_extensions:
  - pymdownx.arithmatex

theme:
  name: material

extra_javascript:
  - https://cdnjs.cloudflare.com/ajax/libs/require.js/2.3.4/require.min.js
  - https://cdnjs.cloudflare.com/ajax/libs/mathjax/2.7.7/MathJax.js?config=TeX-MML-AM_CHTML